UserManagment2/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserManagment2.Models;
using UserManagment2.ViewModels;

namespace UserManagment2.Controllers
{
    [Authorize(Roles = RolesName.AdminRole)]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task <IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        public async Task<IActionResult> Add(RoleFormViewModel model)
        {
            if (!ModelState.IsValid)
                return View("Index", await _roleManager.Roles.ToListAsync());
            var roleIsExists = await _roleManager.RoleExistsAsync(model.Name);
            if (roleIsExists)
            {
                ModelState.AddModelError("Name", "Role is exists!");
                return View("Index", await _roleManager.Roles.ToListAsync());
            }
            await _roleManager.CreateAsync(new IdentityRole(model.Name.Trim()));
            return RedirectToAction(nameof(Index));
        }
    }
}

UserManagment2/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserManagment2.Data;
using UserManagment2.Models;
using UserManagment2.ViewModels;

namespace UserManagment2.Controllers
{
	[Authorize(Roles = RolesName.AdminRole)]
	public class UsersController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly ApplicationDbContext _context;
		 
		public UsersController(UserManager<ApplicationUser> userManager , ApplicationDbContext context)
		{
			_userManager = userManager;
			_context = context;
		}

		public async Task<IActionResult> Index()
		{
			var users = await  _context.Users
				.Select(user=> new UserViewModel()
				{
                    Id = user.Id,
					FirstName = user.FirstName,
					LastName = user.LastName,
					UserName = user.UserName,
					Email = user.Email,
					Roles =   _userManager.GetRolesAsync(user).Result
				})
				.ToListAsync();


			return View(users);
		}
	}
}

UserManagment2/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using UserManagment2.Data;
using UserManagment2.Models;

namespace UserManagment2.Controllers
{
    public class VisitsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        public VisitsController(ApplicationDbContext context, IToastNotification toastNotification)
        {
            _context = context;
            _toastNotification = toastNotification;
        }

        // GET: Visits
        public IActionResult Index(string SearchByUmn)
        {
            IQueryable<Visit> visitsList = _context.Visits.Include(v => v.Patient);
            if (!string.IsNullOrEmpty(SearchByUmn))
            {
                visitsList = visitsList.Where(p => p.Umn.ToLower().Contains(SearchByUmn.ToLower())).Include(v => v.Patient);
            }

            visitsList = visitsList.OrderByDescending(v => v.EntryDate).Take(10);
            return View(visitsList.ToList());

        }

        // GET: Visits/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null || _context.Visits == null)
            {
                return NotFound();
            }

            var visit = _context.Visits
                .Include(v => v.Patient)
                .FirstOrDefault(m => m.VisitId == id);
            if (visit == null)
            {
                return NotFound();
            }

            return View(visit);
        }

        // GET: Visits/Create
        public IActionResult Create(int? id, string umn)
        {
            //ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId");

            //this viewBag for  fetch data from the patient view to visit controller to visit view
            ViewBag.PatientId = id;
            ViewBag.umn = umn;
            return View();
        }

        // POST: Visits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Visit visit)
        {
            //if (ModelState.IsValid)
            //{
            _context.Add(visit);
            _context.SaveChanges();
            _toastNotification.AddSuccessToastMessage("Visit has been added successfully");

            return RedirectToAction("Index", "Patient");
            //}
            //ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId", visit.PatientId);
            //return View(visit);
        }

        // GET: Visits/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null || _context.Visits == null)
            {
                return NotFound();
            }

            var visit = _context.Visits.Find(id);
            if (visit == null)
            {
                return NotFound();
            }
            //ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId", visit.PatientId);
            return View(visit);
        }

        // POST: Visits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("VisitId,PatientId,Umn,TicketNumber,EntryPlace,PaymentType,EntryHour,EntryDate,CurrentLocation")] Visit visit)
        {
            if (id != visit.VisitId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visit);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisitExists(visit.VisitId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                _toastNotification.AddSuccessToastMessage("Visit has been updated successfully");

                return RedirectToAction(nameof(Index));
            }
            //ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId", visit.PatientId);
            return View(visit);
        }

        //// GET: Visits/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null || _context.Visits == null)
        //    {
        //        return NotFound();
        //    }

        //    var visit = await _context.Visits
        //        .Include(v => v.Patient)
        //        .FirstOrDefaultAsync(m => m.VisitId == id);
        //    if (visit == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(visit);
        //}

        //// POST: Visits/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Visits == null)
        //    {
        //        return Problem("Entity set 'HisContext.Visits'  is null.");
        //    }
        //    var visit = await _context.Visits.FindAsync(id);
        //    if (visit != null)
        //    {
        //        _context.Visits.Remove(visit);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool VisitExists(int id)
        {
            return (_context.Visits?.Any(e => e.VisitId == id)).GetValueOrDefault();
        }
    }
}

UserManagment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Health Record</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/UserManagment2.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 nav-wdth" >
			<div class="container-fluid">
				@*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Health Record</a>*@
				@*<img src="~/images/7.png" alt="" class="imno">*@
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/0.jpg" alt="" class="imno"></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						@if (User.IsInRole(RolesName.AdminRole))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Manage Roles</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Manage Users</a>
							</li>
						}
						@if (User.IsInRole(RolesName.AdminRole) || User.IsInRole(RolesName.EmployeeRole))
						{
							<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="patient" asp-action="Index">Receptionist</a>
							</li>
                        
						}
						@if (User.IsInRole(RolesName.AdminRole) || User.IsInRole(RolesName.DoctorRole))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Visits" asp-action="Index">Diagnose</a>
							</li>
						}
					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - Faculty of Computers and Informatics, Zagazig University @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
	@await Component.InvokeAsync("NToastNotify")
</body>
</html>