UserManagment2/Controllers/DiagnosisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using UserManagment2.Data;
using UserManagment2.Models;

namespace UserManagment2.Controllers
{
    //[Authorize(Roles =RolesName.DoctorRole)]
    public class DiagnosisController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;

        public DiagnosisController(ApplicationDbContext context, IToastNotification toastNotification)
        {
            _context = context;
            _toastNotification = toastNotification;
        }

        // GET: Diagnosis
        public IActionResult Index(int id)
        {
            IEnumerable<Diagnosis> hisContext = _context.Diagnoses.Include(d => d.Visit);
            hisContext = hisContext.Where(d => d.VisitId == id).OrderByDescending(i => i.DiagnosisDate);
            return View(hisContext.ToList());
        }

        // GET: Diagnosis/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null || _context.Diagnoses == null)
            {
                return NotFound();
            }

            var diagnosis = _context.Diagnoses
                .Include(d => d.Visit)
                .FirstOrDefault(m => m.DiagnosisId == id);
            if (diagnosis == null)
            {
                return NotFound();
            }

            return View(diagnosis);
        }

        // GET: Diagnosis/Create
        public IActionResult Create(int? id)
        {
            ViewBag.VisitId = id;
            //ViewData["VisitId"] = new SelectList(_context.Visits, "VisitId", "VisitId");
            return View();
        }

        // POST: Diagnosis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Diagnosis diagnosis)
        {
            //if (ModelState.IsValid)
            //{
            _context.Add(diagnosis);
            _context.SaveChanges();
            _toastNotification.AddSuccessToastMessage("Diagnosis added successfully");
            return RedirectToAction("Index", "Visits");
            //}
            //ViewData["VisitId"] = new SelectList(_context.Visits, "VisitId", "VisitId", diagnosis.VisitId);
            //return View(diagnosis);
        }

        // GET: Diagnosis/Edit/5
        public IActionResult Edit(int? id, int visitId)
        {


            if (id == null || _context.Diagnoses == null)
            {
                return NotFound();
            }

            var diagnosis = _context.Diagnoses.Find(id);
            if (diagnosis == null)
            {
                return NotFound();
            }
            ViewBag.visitId = visitId;
            //ViewData["VisitId"] = new SelectList(_context.Visits, "VisitId", "VisitId", diagnosis.VisitId);
            return View(diagnosis);
        }

        // POST: Diagnosis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("DiagnosisId,VisitId,Examiation,Drugs,Tests,Diagnosis1,DoctorDecision,DiagnosisDate,DiagnosisLocation")] Diagnosis diagnosis)
        {

            if (id != diagnosis.DiagnosisId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(diagnosis);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiagnosisExists(diagnosis.DiagnosisId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                _toastNotification.AddSuccessToastMessage("Diagnosis updated successfully");
                return RedirectToAction("Index", "Visits");
            }
            //ViewData["VisitId"] = new SelectList(_context.Visits, "VisitId", "VisitId", diagnosis.VisitId);
            return View(diagnosis);
        }

        //// GET: Diagnosis/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null || _context.Diagnoses == null)
        //    {
        //        return NotFound();
        //    }

        //    var diagnosis = await _context.Diagnoses
        //        .Include(d => d.Visit)
        //        .FirstOrDefaultAsync(m => m.DiagnosisId == id);
        //    if (diagnosis == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(diagnosis);
        //}

        //// POST: Diagnosis/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Diagnoses == null)
        //    {
        //        return Problem("Entity set 'HisContext.Diagnoses'  is null.");
        //    }
        //    var diagnosis = await _context.Diagnoses.FindAsync(id);
        //    if (diagnosis != null)
        //    {
        //        _context.Diagnoses.Remove(diagnosis);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool DiagnosisExists(int id)
        {
            return (_context.Diagnoses?.Any(e => e.DiagnosisId == id)).GetValueOrDefault();
        }
    }
}

UserManagment2/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using UserManagment2.Data;
using UserManagment2.Models;

namespace UserManagment2.Controllers
{
    public class PatientController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        public PatientController(ApplicationDbContext context, IToastNotification toastNotification)
        {
            _context = context;
            _toastNotification = toastNotification;
        }

        // GET: Patient
        public IActionResult Index(string SearchByName)
        {
            var patientList = _context.Patients.ToList();
            if (!string.IsNullOrEmpty(SearchByName))
            {
                patientList = patientList.Where(p => p.PatientName.ToLower().Contains(SearchByName.ToLower())).ToList();
            }
            patientList = patientList.OrderByDescending(p => p.PatientId).Take(10).ToList();
            return View(patientList);
        }

        // GET: Patient/Details/5
        //public IActionResult Details(int? id)
        //{
        //    if (id == null || _context.Patients == null)
        //    {
        //        return NotFound();
        //    }

        //    var patient = _context.Patients.FirstOrDefault(m => m.PatientId == id);
        //    if (patient == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(patient);
        //}

        // GET: Patient/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Patient/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PatientId,NationalId,Umn,PatientName,PatientAge,PatientAddress,PhoneNumber")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                _context.Add(patient);
                _context.SaveChanges();
                _toastNotification.AddSuccessToastMessage("Patient data added successfully");
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        // GET: Patient/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null || _context.Patients == null)
            {
                return NotFound();
            }

            var patient = _context.Patients.Find(id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        // POST: Patient/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("PatientId,NationalId,Umn,PatientName,PatientAge,PatientAddress,PhoneNumber")] Patient patient)
        {
            if (id != patient.PatientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patient);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(patient.PatientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                _toastNotification.AddSuccessToastMessage("Patient data updated successfully");
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        // GET: Patient/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null || _context.Patients == null)
            {
                return NotFound();
            }

            var patient = _context.Patients.FirstOrDefault(m => m.PatientId == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // POST: Patient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (_context.Patients == null)
            {
                return Problem("Entity set 'HisContext.Patients'  is null.");
            }
            var patient = _context.Patients.Find(id);
            if (patient != null)
            {
                _context.Patients.Remove(patient);
            }

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(int id)
        {
            return (_context.Patients?.Any(e => e.PatientId == id)).GetValueOrDefault();
        }
    }
}

UserManagment2/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using UserManagment2.Data;
using UserManagment2.Models;

namespace UserManagment2.Controllers
{
    public class VisitsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        public VisitsController(ApplicationDbContext context, IToastNotification toastNotification)
        {
            _context = context;
            _toastNotification = toastNotification;
        }

        // GET: Visits
        public IActionResult Index(string SearchByUmn)
        {
            IQueryable<Visit> visitsList = _context.Visits.Include(v => v.Patient);
            if (!string.IsNullOrEmpty(SearchByUmn))
            {
                visitsList = visitsList.Where(p => p.Umn.ToLower().Contains(SearchByUmn.ToLower())).Include(v => v.Patient);
            }

            visitsList = visitsList.OrderByDescending(v => v.EntryDate).Take(10);
            return View(visitsList.ToList());

        }

        // GET: Visits/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null || _context.Visits == null)
            {
                return NotFound();
            }

            var visit = _context.Visits
                .Include(v => v.Patient)
                .FirstOrDefault(m => m.VisitId == id);
            if (visit == null)
            {
                return NotFound();
            }

            return View(visit);
        }

        // GET: Visits/Create
        public IActionResult Create(int? id, string umn)
        {
            //ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId");

            //this viewBag for  fetch data from the patient view to visit controller to visit view
            ViewBag.PatientId = id;
            ViewBag.umn = umn;
            return View();
        }

        // POST: Visits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Visit visit)
        {
            //if (ModelState.IsValid)
            //{
            _context.Add(visit);
            _context.SaveChanges();
            _toastNotification.AddSuccessToastMessage("Visit has been added successfully");

            return RedirectToAction("Index", "Patient");
            //}
            //ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId", visit.PatientId);
            //return View(visit);
        }

        // GET: Visits/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null || _context.Visits == null)
            {
                return NotFound();
            }

            var visit = _context.Visits.Find(id);
            if (visit == null)
            {
                return NotFound();
            }
            //ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId", visit.PatientId);
            return View(visit);
        }

        // POST: Visits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("VisitId,PatientId,Umn,TicketNumber,EntryPlace,PaymentType,EntryHour,EntryDate,CurrentLocation")] Visit visit)
        {
            if (id != visit.VisitId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visit);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisitExists(visit.VisitId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                _toastNotification.AddSuccessToastMessage("Visit has been updated successfully");

                return RedirectToAction(nameof(Index));
            }
            //ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId", visit.PatientId);
            return View(visit);
        }

        //// GET: Visits/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null || _context.Visits == null)
        //    {
        //        return NotFound();
        //    }

        //    var visit = await _context.Visits
        //        .Include(v => v.Patient)
        //        .FirstOrDefaultAsync(m => m.VisitId == id);
        //    if (visit == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(visit);
        //}

        //// POST: Visits/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Visits == null)
        //    {
        //        return Problem("Entity set 'HisContext.Visits'  is null.");
        //    }
        //    var visit = await _context.Visits.FindAsync(id);
        //    if (visit != null)
        //    {
        //        _context.Visits.Remove(visit);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool VisitExists(int id)
        {
            return (_context.Visits?.Any(e => e.VisitId == id)).GetValueOrDefault();
        }
    }
}

UserManagment2/Views/Visits/Create.cshtml
@model UserManagment2.Models.Visit
@{
    ViewData["Title"] = "Add Visit";
}


<div class="row container">
    <div class="col-md-4 container">
        <form asp-action="Create">
            <h1>Add Visit</h1>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="PatientId" class="control-label"></label>*@
                <input type="hidden" asp-for="PatientId" class="form-control" value="@ViewBag.PatientId" readonly/>
            </div>
            <div class="form-group">
                <label asp-for="Umn" class="control-label"></label>
                <input  asp-for="Umn" class="form-control" value="@ViewBag.umn" readonly />
                <span asp-validation-for="Umn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketNumber" class="control-label"></label>
                <input asp-for="TicketNumber" class="form-control" />
                <span asp-validation-for="TicketNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryPlace" class="control-label"></label>
                <input asp-for="EntryPlace" class="form-control" />
                <span asp-validation-for="EntryPlace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentType" class="control-label"></label>
                <input asp-for="PaymentType" class="form-control" />
                <span asp-validation-for="PaymentType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrentLocation" class="control-label"></label>
                <input asp-for="CurrentLocation" class="form-control" />
                <span asp-validation-for="CurrentLocation" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" style="width:150px" />
                <a asp-controller="Patient" asp-action="Index"class="btn btn-secondary" style="width:150px">Back to List</a>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <img src="~/images/1.png" alt="Docter" class="w-100">
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

UserManagment2/Views/Visits/Delete.cshtml
@model UserManagment2.Models.Visit

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Visit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Umn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Umn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryPlace)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryPlace)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Patient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Patient.PatientId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VisitId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

UserManagment2/Views/Visits/Details.cshtml
@model UserManagment2.Models.Visit

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Visit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Umn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Umn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryPlace)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryPlace)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Patient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Patient.PatientId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.VisitId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

UserManagment2/Views/Visits/Edit.cshtml
@model UserManagment2.Models.Visit

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit visit</h1>

<h4>Visit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @*<input type="hidden" asp-for="VisitId" />
            <div class="form-group">
                <label asp-for="PatientId" class="control-label"></label>
                <select asp-for="PatientId" class="form-control" asp-items="ViewBag.PatientId"></select>
                <span asp-validation-for="PatientId" class="text-danger"></span>
            </div>*@

            <div class="form-group">
                <label asp-for="Umn" class="control-label"></label>
                <input asp-for="Umn" class="form-control" readonly />
                <span asp-validation-for="Umn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketNumber" class="control-label"></label>
                <input asp-for="TicketNumber" class="form-control" />
                <span asp-validation-for="TicketNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryPlace" class="control-label"></label>
                <input asp-for="EntryPlace" class="form-control" />
                <span asp-validation-for="EntryPlace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentType" class="control-label"></label>
                <input asp-for="PaymentType" class="form-control" />
                <span asp-validation-for="PaymentType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryDate" class="control-label"></label>
                <input asp-for="EntryDate" class="form-control" />
                <span asp-validation-for="EntryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrentLocation" class="control-label"></label>
                <input asp-for="CurrentLocation" class="form-control" />
                <span asp-validation-for="CurrentLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" style="width:150px" />
                <a asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UserManagment2/Views/Visits/Index.cshtml
@model IEnumerable<UserManagment2.Models.Visit>

@{
    ViewData["Title"] = "Index";
}



@*search *@


<div class="container p-3">
    <div class="row pt-4">
        <h1>Patient visits</h1>
    </div>
    <div class="row pt-4">
        <div class="col-6 text-center" >
            @using (Html.BeginForm())
            {
            <div class="input-group">
                    @Html.TextBox("SearchByUmn",null,new{ @class="form-control",@placeholder="Search By patient Medical Number ...."})
                <input type="submit" value="Search" class="btn btn-outline-success">
            </div>
            }
        </div>
        <div class="col-6 text-end" >
           
        </div>
    </div>

    <br /> 

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr class="bg-primary text-white">
                <th>
                        @Html.DisplayNameFor(model=>model.Patient.PatientName)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.Umn)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.TicketNumber)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.EntryPlace)
                </th>
                    @*<th>
                    @Html.DisplayNameFor(model => model.PaymentType)
                </th>*@
                <th>
                        @Html.DisplayNameFor(model => model.EntryDate)
                </th>
                    @*<th>
                    @Html.DisplayNameFor(model => model.CurrentLocation)
                </th>*@
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                        @Html.DisplayFor(modelItem => item.Patient.PatientName)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Umn)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.TicketNumber)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.EntryPlace)
                </td>
                    @*<td>
                @Html.DisplayFor(modelItem => item.PaymentType)
            </td>*@
                <td>
                        @Html.DisplayFor(modelItem => item.EntryDate)
                </td>
                    @*<td>
                @Html.DisplayFor(modelItem => item.CurrentLocation)
            </td>*@
                <td>
                        <a asp-controller="Diagnosis" asp-action="Create" asp-route-id="@item.VisitId" class="btn btn-sm btn-primary">Add Diagnosis</a> | 
                        <a asp-controller="Diagnosis" asp-action="Index" asp-route-id="@item.VisitId" class="btn btn-sm btn-secondary">View Diagnosis</a> 
                        @*<a asp-action="Details" asp-route-id="@item.VisitId" class="btn btn-sm btn-outline-secondary">Details</a> |*@
                        @*<a asp-action="Delete" asp-route-id="@item.VisitId" class="btn btn-sm btn-danger">Delete</a>*@
                </td>
            </tr>
            }
        </tbody>
    </table>

</div>